services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_PATH=${DATABASE_PATH}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    volumes:
      - /opt/enterio/flowise_data:/root/.flowise
