services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    environment:
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_PATH=${DATABASE_PATH}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    volumes:
      - /opt/enterio/flowise_data:/root/.flowise

  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    restart: unless-stopped
    depends_on:
      - flowise
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - FLOWISE_URL=http://flowise:3000
      - CHATFLOW_ID=${CHATFLOW_ID}
    volumes:
      - ./.env:/app/.env:ro
